# Generated by Django 5.2.7 on 2025-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='residence',
            field=models.CharField(choices=[('school', 'Lives in School'), ('outside', 'Lives Outside School')], default='school', max_length=10),
        ),
    ]
